name: aims-ml
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - pip
  - pytorch=0.4.1
  - torchvision
  - opencv
  - matplotlib
  - jupyter
  - pip:
    - torchtext
    - torchviz
